make: 
	sudo apt install build-essential pkg-config cmake cmake-data libsdl2-dev libsdl2-image-dev
	sudo apt install libsdl2-ttf-dev libsdl2-net-dev libsdl2-mixer-dev libsdl2-gfx-dev
	cmake ../CMakeLists.txt
	make -C ../
